global Blocks nBlocks;
global LEFT RIGHT UP DOWN;
global LEFT_UP LEFT_DOWN RIGHT_UP RIGHT_DOWN UP_LEFT UP_RIGHT DOWN_LEFT DOWN_RIGHT
global LEFT_MIN RIGHT_MIN UP_MIN DOWN_MIN
global MAX_NUM_BR
global FigMesh kQTFct kQTnx kQTny  kQTdx kQTdy